package com.freelancing.entity.enums;

public enum NotificationType {
    JOB_POSTED,
    PROPOSAL_RECEIVED,
    PROPOSAL_ACCEPTED,
    PROPOSAL_REJECTED,
    CONTRACT_STARTED,
    CONTRACT_COMPLETED,
    MILESTONE_SUBMITTED,
    MILESTONE_APPROVED,
    PAYMENT_RECEIVED,
    MESSAGE_RECEIVED,
    DISPUTE_OPENED,
    DISPUTE_RESOLVED,
    SYSTEM
}
